### PR TITLE
This is a big change from a product POV. Leverage the entire network, not just posts created by the extension.

### PR DESCRIPTION
**Pull request by adamatic-me**
This is closer to what I would like from a product pov, but it's a big departure. I would certainly understand if you choose not to merge this idea.

I changed searchForPost to find the top post on all of Bsky which contains this tab's url. This way it uses the whole network, and not just posts created by the extension.

If anyone would like to try it out, install the dist folder [here](https://github.com/adamatic-me/bluesky-comments-chrome/tree/main). 

Example URL to try this on, with a ton of existing content: https://www.nytimes.com/2024/11/22/technology/bluesky-x-alternative.html

image

### To Do: 

- [x] 1) In popup, ideally the top level parent post and its text content would also be on top of all the replies. On click of post text, the post is opened on bsky.app. It would replace the "Reply on Bluesky here..." functionality. On click of any reply comment text, that specific comment is opened on bsky.app.

- [x] 2) Change the create new post behavior. Allow the user to write their own post text via an in-popup text area. No tag is necessary now. 

- [ ] 2.1) In the future, explore creating the [link card via API](https://docs.bsky.app/docs/tutorials/creating-a-post#website-card-embeds).

- [ ] 3) Change the search limit to ~20, and in popup use something like status-container on top to show a **< 1 of n posts >** nav bar, to navigate through all returned top-level posts?

Thanks for your consideration and making this extension!

### CODE REVIEW

**Comment by adamatic-me** [comment]
Oh, I just realized possibly the first To Do could be to add a link somewhere to create your own post even if one already exists.

**Comment by adamatic-me** [comment]
These are my first open source contribution attempts, so sorry if I am breaking decorum by adding more and more commits to the same PR. Please let me know.

**Comment by adamatic-me** [comment]
I think I likely greatly bodged the container elements in [ed80572](https://github.com/joneslloyd/bluesky-comments-chrome/pull/2/commits/ed805723b4d4141805b0478a18521f3a58035d7e).  That one probably needs the closest look.

**Comment by joneslloyd** [comment]
Sorry, it was closed automatically. Not my intention.

I don't think that this is quite a divergence from a product POV, and isn't something I'd like to do with Bluniversal Comments.

It's really cool as an idea though!

**Pull request closed without merging**
